name: testz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animate_gradient: ^0.0.2+1
  animated_text_kit: ^4.2.2
  audio_service: ^0.18.12
  audio_session: ^0.1.18
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  carousel_slider: ^4.2.1
  device_info_plus: ^8.2.2
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_foreground_task: ^6.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^16.3.2
  flutter_native_splash: ^2.3.10
  google_fonts: ^6.1.0
  http: ^1.2.1
  image: ^4.1.7
  intl: ^0.19.0
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  loading_animation_widget: ^1.2.0+4
  mongo_dart: ^0.10.0
  new_pinput: ^1.0.1
  palette_generator: ^0.3.3+3
  permission_handler: ^11.3.0
  rxdart: ^0.27.7
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.2
  spotify: ^0.13.1
  video_player: ^2.8.2
  wakelock: ^0.6.2
  youtube_explode_dart: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true

flutter_native_splash:
  color: "#000000"
  image: assets/splash.png
  color_dark: "#000000"
  image_dark: assets/splash.png
  android_12:
    image : assets/splash.png
    color: "#000000"
    image_dark: assets/splash.png
    color_dark: "#000000"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/summervibe.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/summervibe.png"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/summervibe.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/summervibe.png"
