// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANuYbxMVk36eicdnxeMC6DfkoXKyCuCbc',
    appId: '1:989361670872:web:7d8c58dbb701d629b665ad',
    messagingSenderId: '989361670872',
    projectId: 'emoapp-4be99',
    authDomain: 'emoapp-4be99.firebaseapp.com',
    storageBucket: 'emoapp-4be99.appspot.com',
    measurementId: 'G-FDBPP8SGTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-I7KMtNmm_HZKl090GkiUqkMXfQ8RbL8',
    appId: '1:989361670872:android:837c2cc931c99e8db665ad',
    messagingSenderId: '989361670872',
    projectId: 'emoapp-4be99',
    storageBucket: 'emoapp-4be99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlWMdenL4tT8KM_v2PUdg9iImjAfUkl9c',
    appId: '1:989361670872:ios:bb65aa0348f4b022b665ad',
    messagingSenderId: '989361670872',
    projectId: 'emoapp-4be99',
    storageBucket: 'emoapp-4be99.appspot.com',
    iosBundleId: 'com.example.testz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlWMdenL4tT8KM_v2PUdg9iImjAfUkl9c',
    appId: '1:989361670872:ios:8bc77e9d92a06d4eb665ad',
    messagingSenderId: '989361670872',
    projectId: 'emoapp-4be99',
    storageBucket: 'emoapp-4be99.appspot.com',
    iosBundleId: 'com.example.testz.RunnerTests',
  );
}
